config/routes.rb
Rails.application.routes.draw do
  root 'gifs#index'
  resources :gifs
  get 'tag/*tag', to: 'gifs#by_tag', as: :gif_by_tag
  resources :users, only: [:index, :show]

  devise_for :users

  resources :articles do
    resources :comments
  end

  get '/home', to: 'landing_page#index', as: 'home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :article

  validates :commenter, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  included do
    VALID_STATUSES = ['public', 'private', 'archived']

    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/gif.rb
class Gif < ApplicationRecord
  include ImageUploader::Attachment(:image)
  belongs_to :user

  acts_as_taggable_on :tags

  scope :sorted, -> { order(created_at: :desc) }

  def self.random
    order("RANDOM()").all
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_person_name
  has_many :gifs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true
#
# This is the doc for Article controller
# The docs also
#   Article.count
class ArticlesController < ApplicationController
  http_basic_authenticate_with name: "mahfuz", password: "secret", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "mahfuz", password: "secret", only: :destroy
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)

    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy

    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_gif, only: [:edit, :update, :destroy]

  # GET /gifs
  # GET /gifs.json
  def index
    @gifs = Gif.includes(:tags, :user).sorted
  end

  # GET /gifs/1
  # GET /gifs/1.json
  def show
    @gif = Gif.find(params[:id])
  end

  def by_tag
    @gifs = Gif.tagged_with(params[:tag]).random
    @gifs ||= Gif.random

    render :index
  end

  # GET /gifs/new
  def new
    @gif = Gif.new
  end

  # GET /gifs/1/edit
  def edit
  end

  # POST /gifs
  # POST /gifs.json
  def create
    @gif = current_user.gifs.new(gif_params)

    respond_to do |format|
      if @gif.save
        format.html { redirect_to @gif, notice: 'Gif was successfully created.' }
        format.json { render :show, status: :created, location: @gif }
      else
        format.html { render :new }
        format.json { render json: @gif.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gifs/1
  # PATCH/PUT /gifs/1.json
  def update
    respond_to do |format|
      if @gif.update(gif_params)
        format.html { redirect_to @gif, notice: 'Gif was successfully updated.' }
        format.json { render :show, status: :ok, location: @gif }
      else
        format.html { render :edit }
        format.json { render json: @gif.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifs/1
  # DELETE /gifs/1.json
  def destroy
    @gif.destroy
    respond_to do |format|
      format.html { redirect_to gifs_url, notice: 'Gif was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gif
      @gif = current_user.gifs.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gif_params
      params.require(:gif).permit(:image, :tag_list)
    end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:index, :show]

  def index
    redirect_to root_path
  end

  def show
    @gifs = @user.gifs.includes(:tags, :user).sorted

    render "gifs/index"
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gifs_helper.rb
module GifsHelper
  def linked_tag_list(gif)
    list = gif.tags.map do |tag|
      link_to tag.name, gif_by_tag_path(tag: tag.name),
              :class => "py-1 px-3 shadow-md no-underline rounded-full bg-green-500 text-gray-700 text-xs shadow border-green btn-primary hover:text-white hover:bg-green-400 focus:outline-none active:shadow-none mr-2"
    end

    safe_join(list)
  end
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<p><%= Article.public_count %> articles and counting!</p>
<hr>
<%= link_to "New Article", new_article_path %>

<ul>
  <% @articles.each do |article| %>
    <% unless article.archived? %>
      <li>
        <%= link_to article.title, article %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1>
  <%= @article.title %>
</h1>
<p>
  <%= @article.body %>
</p>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li>
    <%= link_to "Destroy", article_path(@article),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
  </li>
</ul>

<h2>Comments</h2>
<%= render @article.comments %>

<hr>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
              :method => :delete,
              data: { confirm: "Are you sure?" } %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/gifs/_form.html.erb
<%= form_with(model: gif, local: true) do |form| %>
  <% if gif.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gif.errors.count, "error") %> prohibited this gif from being saved:</h2>

      <ul>
        <% gif.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.hidden_field :image, value: form.object.cached_image_data %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :tag_list %>
    <%= form.text_field :tag_list, value: form.object.tag_list.join(', ') %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<!--<div class="h-screen font-sans text-gray-900 bg-gray-300 border-box">-->
<!--  <div class="flex justify-center w-full mx-auto sm:max-w-lg">-->

<!--    <div class="flex flex-col items-center justify-center w-full h-auto my-20 bg-white sm:w-3/4 sm:rounded-lg sm:shadow-xl">-->
<!--      <div class="mt-10 mb-10 text-center">-->
<!--        <h2 class="text-2xl font-semibold mb-2">Upload your files</h2>-->
<!--        <p class="text-xs text-gray-500">File should be of format .gif, .jpg, .png or .jpeg</p>-->
<!--      </div>-->

      <%#= form_with(model: gif, local: true, :html => { class: "relative w-4/5 h-32 max-w-xs mb-10 bg-white bg-gray-100 rounded-lg shadow-inner" }) do |form| %>
        <%# if gif.errors.any? %>
<!--          <div id="error_explanation">-->
<!--            <h2><%#= pluralize(gif.errors.count, "error") %> prohibited this gif from being saved:</h2>-->

<!--            <ul>-->
              <%# gif.errors.full_messages.each do |message| %>
<!--                <li><%#= message %></li>-->
              <%# end %>
<!--            </ul>-->
<!--          </div>-->
        <%# end %>

<!--        <div class="hidden">-->
          <%#= form.hidden_field :image, value: form.object.cached_image_data %>
<!--        </div>-->

        <%#= form.file_field :image, :class => "hidden" %>
<!--        <label for="gif_image" class="z-20 flex flex-col-reverse items-center justify-center w-full h-full cursor-pointer">-->
<!--          <p class="z-10 text-xs font-light text-center text-gray-500">Drag & Drop your files here</p>-->
<!--          <svg class="z-10 w-8 h-8 text-indigo-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">-->
<!--            <path d="M2 6a2 2 0 012-2h5l2 2h5a2 2 0 012 2v6a2 2 0 01-2 2H4a2 2 0 01-2-2V6z"></path>-->
<!--          </svg>-->
<!--        </label>-->

        <%#= form.text_field :tag_list, value: form.object.tag_list.join(', '), :class => "w-full px-2 py-1 lg:px-4 lg:py-2 text-gray-700 bg-gray-100 text-xs lg:text-sm border border-gray-300 rounded-lg focus:outline-none focus:bg-white" %>
        <%#= form.submit :class => "h-auto lg:h-12 text-xs py-1 lg:py-2 px-2 lg-px-4 text-white font-light tracking-wider bg-gray-900 rounded-lg uppercase w-full focus:outline-none focus:shadow-outline" %>
      <%# end %>

<!--    </div>-->
<!--  </div>-->
<!--</div>-->

app/views/gifs/edit.html.erb
<h1>Editing Gif</h1>

<%= render 'form', gif: @gif %>

<%= link_to 'Show', @gif %> |
<%= link_to 'Back', gifs_path %>

app/views/gifs/index.html.erb
<p id="notice"><%= notice %></p>

<%#= gif.user_id %>
<%#= gif.image_data %>

<!-- component -->
<div class="container mx-auto p-8">
  <div class="flex flex-wrap justify-center">
    <% @gifs.each do |gif| %>
      <div class="w-64 m-4 shadow rounded">
        <%= link_to image_tag(gif.image_url), gif, :class => "mx-auto" %>
        <div class="text-gray-700 text-sm">
          Uploaded by: <%= link_to gif.user.name, gif.user %>
        </div>
        <div class="p-2">
          <%= linked_tag_list gif %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/gifs/new.html.erb
<%= render 'form', gif: @gif %>

<%= link_to 'Back', gifs_path %>

app/views/gifs/show.html.erb
<div class="w-auto container mx-auto">
  <p id="notice"><%= notice %></p>
  <%= image_tag @gif.image_url, :class => "object-center" %>

  <div class="flex text-xs justify-content">
    <div class="mr-2">Uploaded by:  <%= link_to @gif.user.name, @gif.user %></div>
    <div class="">
      <% if user_signed_in? && current_user.id == @gif.user_id %>
        <%= link_to 'Edit', edit_gif_path(@gif), class: "mr-2" %>|
        <%= link_to 'Destroy', @gif, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>

  </div>
  <div class="mb-1">
    <%= linked_tag_list @gif %>
  </div>

  <div class="relative flex w-1/3 flex-wrap items-stretch mb-3">
    <%= text_field_tag nil, @gif.image_url(host: root_url), id: "gif_url", :class => "px-3 py-3 placeholder-gray-400 text-gray-700 relative bg-white bg-white rounded text-sm shadow outline-none focus:outline-none focus:shadow-outline w-full pr-10" %>
    <span data-clipboard-target="#gif_url" data-tippy-content="Copy to clipboard"
      class="btn cursor-pointer bg-gray-300 px-2 tooltip z-10 h-full leading-snug font-normal absolute text-center text-gray-400 absolute bg-transparent rounded text-base items-center justify-center w-16 right-0 pr-3 py-3">
      Copy
    </span>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav x-data="{ open: false }"
     @keydown.window.escape="open = false"
     class="bg-gray-800"
>
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <div class="flex items-center">
        <div class="flex-shrink-0">
          <a class="relative flex items-center inline-block h-5 h-full font-black leading-none" href="<%= url_for root_path %>">
            <svg class="w-auto h-6 text-indigo-600 fill-current" viewBox="0 0 194 116"
                 xmlns="http://www.w3.org/2000/svg">
              <g fill-rule="evenodd">
                <path
                  d="M96.869 0L30 116h104l-9.88-17.134H59.64l47.109-81.736zM0 116h19.831L77 17.135 67.088 0z" />
                <path d="M87 68.732l9.926 17.143 29.893-51.59L174.15 116H194L126.817 0z" />
              </g>
            </svg>
            <span class="ml-3 text-xl text-white">Gifs<span class="text-pink-500">.</span></span>
          </a>
        </div>
        <div class="hidden md:block">
          <div class="ml-10 flex items-baseline">
            <a href="#" class="px-3 py-2 rounded-md text-sm font-medium text-white bg-gray-900 focus:outline-none focus:text-white focus:bg-gray-700">Dashboard</a>
            <a href="#" class="ml-4 px-3 py-2 rounded-md text-sm font-medium text-gray-300 hover:text-white hover:bg-gray-700 focus:outline-none focus:text-white focus:bg-gray-700">Team</a>
            <a href="#" class="ml-4 px-3 py-2 rounded-md text-sm font-medium text-gray-300 hover:text-white hover:bg-gray-700 focus:outline-none focus:text-white focus:bg-gray-700">Projects</a>
            <a href="#" class="ml-4 px-3 py-2 rounded-md text-sm font-medium text-gray-300 hover:text-white hover:bg-gray-700 focus:outline-none focus:text-white focus:bg-gray-700">Calendar</a>
            <a href="#" class="ml-4 px-3 py-2 rounded-md text-sm font-medium text-gray-300 hover:text-white hover:bg-gray-700 focus:outline-none focus:text-white focus:bg-gray-700">Reports</a>
          </div>
        </div>
      </div>

      <% if user_signed_in? %>

        <div class="hidden md:block">
          <div class="ml-4 flex items-center md:ml-6">
            <a href="<%= url_for new_gif_path %>" class="relative mb-5 mr-3 sm:mb-0">
              <span class="absolute top-0 left-0 w-full h-full mt-1 ml-1 bg-black rounded"></span>
              <span class="relative inline-block w-full h-full px-3 py-1 text-base font-bold transition duration-100 bg-white border-2 border-black rounded fold-bold hover:bg-yellow-400 hover:text-gray-900">
                Upload
              </span>
            </a>

            <button class="p-1 border-2 border-transparent text-gray-400 rounded-full hover:text-white focus:outline-none focus:text-white focus:bg-gray-700">
              <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
              </svg>
            </button>

            <div @click.away="open = false"
                 x-data="{ open: false }"
                 class="ml-3 relative"
            >
              <div>
                <button @click="open = !open" class="max-w-xs flex items-center text-sm rounded-full text-white focus:outline-none focus:shadow-solid">
                  <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" />
                </button>
              </div>
              <div x-show="open"
                   x-transition:enter="transition ease-out duration-100"
                   x-transition:enter-start="transform opacity-0 scale-95"
                   x-transition:enter-end="transform opacity-100 scale-100"
                   x-transition:leave="transition ease-in duration-75"
                   x-transition:leave-start="transform opacity-100 scale-100"
                   x-transition:leave-end="transform opacity-0 scale-95"
                   class="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg"
              >
                <div class="py-1 rounded-md bg-white shadow-xs">
                  <%= link_to edit_user_registration_path class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100", role: "menuitem" %>
                  <%= link_to 'Upload', new_gif_path, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100", role: "menuitem" %>
                  <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100", role: "menuitem" %>
                </div>
              </div>
            </div>
          </div>
        </div>

      <% else %>

        <div class="hidden md:block">
          <div class="ml-4 flex items-center md:ml-6">
            <%= link_to 'Register', new_user_registration_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
            <%= link_to 'Sign in', new_user_session_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
          </div>
        </div>

      <% end %>

      <div class="-mr-2 flex md:hidden">
        <button @click="open = !open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:bg-gray-700 focus:text-white">
          <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
            <path :class="{'hidden': open, 'inline-flex': !open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
            <path :class="{'hidden': !open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  </div>
  <div :class="{'block': open, 'hidden': !open}"
       class="hidden md:hidden"
  >
    <div class="px-2 pt-2 pb-3 sm:px-3">
      <a href="#" class="block px-3 py-2 rounded-md text-base font-medium text-white bg-gray-900 focus:outline-none focus:text-white focus:bg-gray-700">Dashboard</a>
      <a href="#" class="mt-1 block px-3 py-2 rounded-md text-base font-medium text-gray-300 hover:text-white hover:bg-gray-700 focus:outline-none focus:text-white focus:bg-gray-700">Team</a>
      <a href="#" class="mt-1 block px-3 py-2 rounded-md text-base font-medium text-gray-300 hover:text-white hover:bg-gray-700 focus:outline-none focus:text-white focus:bg-gray-700">Projects</a>
      <a href="#" class="mt-1 block px-3 py-2 rounded-md text-base font-medium text-gray-300 hover:text-white hover:bg-gray-700 focus:outline-none focus:text-white focus:bg-gray-700">Calendar</a>
      <a href="#" class="mt-1 block px-3 py-2 rounded-md text-base font-medium text-gray-300 hover:text-white hover:bg-gray-700 focus:outline-none focus:text-white focus:bg-gray-700">Reports</a>
    </div>

    <% if user_signed_in? %>

      <div class="pt-4 pb-3 border-t border-gray-700">
        <div class="flex items-center px-5">
          <div class="flex-shrink-0">
            <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" />
          </div>
          <div class="ml-3">
            <div class="text-base font-medium leading-none text-white"><%= current_user.name %></div>
            <div class="mt-1 text-sm font-medium leading-none text-gray-400"><%= current_user.email %></div>
          </div>
        </div>
        <div class="mt-3 px-2">
          <%= link_to 'Profile', edit_user_registration_path, class: "block px-3 py-2 rounded-md text-base font-medium text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:text-white focus:bg-gray-700" %>
          <%= link_to 'Upload', new_gif_path, class: "mt-1 block px-3 py-2 rounded-md text-base font-medium text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:text-white focus:bg-gray-700" %>
          <%= link_to destroy_user_session_path, class: "mt-1 block px-3 py-2 rounded-md text-base font-medium text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:text-white focus:bg-gray-700" %>
        </div>
      </div>

    <% else %>
      <div class="pt-1 pb-3 border-t border-gray-700">
        <div class="mt-3 px-2">
          <%= link_to 'Register', new_user_registration_path, class: "block px-3 py-2 rounded-md text-base font-medium text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:text-white focus:bg-gray-700" %>
          <%= link_to 'Sign in', new_user_session_path, class: "mt-1 block px-3 py-2 rounded-md text-base font-medium text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:text-white focus:bg-gray-700" %>
        </div>
      </div>
    <% end %>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Animated Gifs.</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="overflow-x-hidden antialiased bg-gray-200">
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <%= render 'layouts/footer' %>

    <script>
      tippy('.tooltip', {
          content: '[data-tippy-content]',
          animation: 'scale',
      });

      new ClipboardJS('.btn')
    </script>
  </body>
</html>